"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

const gold="#d4a574", dim="#a98b68";
const words=["Strong","Patient","Generous","Funny","Reliable","Protective","Hardworking","Family","Wisdom","Courage","Steady","Faithful","Resilient","Kind","Present","Brave","Humble","Loyal","Provider","Guide","Brother","Husband","Father","Uncle","Friend","Mentor","Leader","Teacher","Builder","Helper","Listener","Example","Strength","Sacrifice","Service","Grace","Purpose","Character","Integrity","Warmth","Patience","Hope","Discipline","Vision","Care","Trust","Legacy","Love","Home","Foundation","50"];
const placeholder=(label:string,sub:string)=>({label,sub});
function Nav({onBack,onNext,first,last}:{onBack?:()=>void;onNext?:()=>void;first?:boolean;last?:boolean}){return <div className="flex justify-between items-center w-full max-w-4xl mt-12 text-sm tracking-widest uppercase"><button onClick={onBack} className={first?"invisible":"text-white/35 hover:text-white/70 transition"}>← Back</button>{!last&&<button onClick={onNext} className="text-[#d4a574] hover:text-white transition">Continue →</button>}</div>}
function Shell({children,eyebrow,title,onBack,onNext,first,last}:{children:React.ReactNode;eyebrow?:string;title?:string;onBack?:()=>void;onNext?:()=>void;first?:boolean;last?:boolean}){return <section className="min-h-screen px-6 py-16 md:py-24 flex flex-col items-center justify-center relative overflow-hidden"><div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_50%_20%,rgba(212,165,116,.09),transparent_42%)]"/><div className="relative z-10 w-full max-w-5xl"><div className="text-center mb-12">{eyebrow&&<p className="text-[#d4a574] text-[11px] tracking-[.35em] uppercase mb-4">{eyebrow}</p>}{title&&<h2 className="text-4xl md:text-6xl font-serif font-light tracking-tight">{title}</h2>}</div>{children}<Nav {...{onBack,onNext,first,last}}/></div></section>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl border border-white/10 bg-white/[.035] backdrop-blur-xl shadow-2xl ${className}`}>{children}</div>}
export default function FiftiethExperience({config}:{config:any}){
 const [step,setStep]=useState(0),[open,setOpen]=useState<number|null>(null),[archive,setArchive]=useState(false);
 const s=config.sections, next=()=>{setOpen(null);setStep(x=>Math.min(11,x+1));},back=()=>{setOpen(null);setStep(x=>Math.max(0,x-1));};
 const roles=s.roles.items||[], memories=s.unknown.memories||[], voices=s.familyVoices.voices||[];
 return <main className="min-h-screen bg-[#090909] text-[#f5f0eb] overflow-hidden selection:bg-[#d4a574]/30">
  <AnimatePresence mode="wait">
   <motion.div key={step} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-18}} transition={{duration:.65}}>
    {step===0&&<section className="h-[100svh] min-h-[620px] flex items-center justify-center px-5 text-center bg-black overflow-hidden"><div className="w-full max-w-3xl -translate-y-1"><motion.div initial={{opacity:0,scale:.68,y:24}} animate={{opacity:1,scale:1,y:0}} transition={{duration:1.55,ease:[.16,1,.3,1]}} className="text-[7rem] sm:text-[9rem] md:text-[13rem] leading-none font-serif font-bold tracking-[-.09em]">50</motion.div><motion.p initial={{opacity:0,scale:.82,y:12}} animate={{opacity:1,scale:1,y:0}} transition={{delay:1.2,duration:1,ease:[.16,1,.3,1]}} className="text-[#d4a574] text-base sm:text-xl md:text-3xl font-serif tracking-[.18em]">1976 → 2026</motion.p><div className="mt-7 sm:mt-9 space-y-2 sm:space-y-3 text-lg sm:text-xl md:text-2xl font-serif text-white/65">{["50 years.","18,250 days.","A lifetime of mornings.","A lifetime of decisions."].map((x,i)=><motion.p key={x} initial={{opacity:0,scale:.88,y:12}} animate={{opacity:1,scale:1,y:0}} transition={{delay:1.9+i*.82,duration:.82,ease:[.16,1,.3,1]}}>{x}</motion.p>)}</div><motion.p initial={{opacity:0,scale:.9,y:14}} animate={{opacity:1,scale:1,y:0}} transition={{delay:5.55,duration:1.15,ease:[.16,1,.3,1]}} className="mt-5 sm:mt-7 text-xl sm:text-2xl md:text-3xl font-serif text-white">And one family that has a lot to thank you for.</motion.p><motion.div initial={{opacity:0,scale:.9,y:18}} animate={{opacity:1,scale:1,y:0}} transition={{delay:6.9,duration:1.2,ease:[.16,1,.3,1]}} className="mt-7 sm:mt-9"><p className="text-[#d4a574] uppercase tracking-[.3em] text-[10px] sm:text-xs mb-2">Happy 50th Birthday</p><h1 className="text-4xl sm:text-5xl md:text-7xl font-serif">{config.name}</h1><p className="mt-3 sm:mt-4 text-white/50 font-serif text-sm sm:text-base md:text-lg">Tonight, we're not just celebrating your birthday.<br/>We're celebrating your story.</p><motion.button initial={{opacity:0,scale:.72}} animate={{opacity:1,scale:1}} transition={{delay:8.45,duration:1,ease:[.16,1,.3,1]}} onClick={next} className="mt-5 sm:mt-7 px-8 py-3 rounded-full border border-[#d4a574]/50 bg-[#d4a574]/10 text-[#d4a574] tracking-widest uppercase text-[10px] hover:bg-[#d4a574]/20 transition">{s.opening.buttonText}</motion.button></motion.div></div></section>}
    {step===1&&<Shell eyebrow="Chapter I" title={s.before.title} onNext={next} onBack={back}><div className="grid md:grid-cols-3 gap-5">{(s.before.photos||[]).map((p:any,i:number)=><motion.div key={i} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:i*.15}}><Card className="overflow-hidden"><div className="aspect-[4/5] flex flex-col items-center justify-center bg-gradient-to-b from-white/[.08] to-black/30"><div className="w-16 h-16 rounded-full border border-[#d4a574]/35 flex items-center justify-center text-[#d4a574] text-2xl">{i+1}</div><p className="mt-4 text-[10px] tracking-[.3em] uppercase text-white/35">Photograph placeholder</p></div><div className="p-5"><p className="text-[#d4a574] font-mono text-sm">{p.year}</p><p className="mt-2 font-serif text-lg text-white/75">{p.caption}</p></div></Card></motion.div>)}</div><p className="text-center text-white/35 text-sm mt-8">Childhood · school · family · work · marriage · milestones</p></Shell>}
    {step===2&&<Shell eyebrow="Chapter II" title={s.roles.title} onNext={next} onBack={back}><div className="grid grid-cols-2 md:grid-cols-3 gap-4">{roles.map((r:any,i:number)=><motion.button key={r.role} whileTap={{scale:.98}} onClick={()=>setOpen(open===i?null:i)} className={`text-left p-6 rounded-2xl border transition ${open===i?"border-[#d4a574]/60 bg-[#d4a574]/10":"border-white/10 bg-white/[.03] hover:bg-white/[.06]"}`}><p className="text-[#d4a574] text-xs tracking-[.25em]">{r.role}</p><AnimatePresence>{open===i&&<motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}} className="mt-5 text-white/70 font-serif leading-relaxed">{r.message}</motion.p>}</AnimatePresence></motion.button>)}</div><p className="text-center text-white/30 text-sm mt-8">Tap a role. Let the man behind the title appear.</p></Shell>}
    {step===3&&<Shell eyebrow="Your Chapter" title={s.yourChapter.title} onNext={next} onBack={back}><Card className="max-w-3xl mx-auto p-8 md:p-14"><div className="space-y-7">{s.yourChapter.paragraphs.map((p:string,i:number)=><motion.p key={i} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.18}} className={`font-serif leading-relaxed ${i===s.yourChapter.paragraphs.length-1?"text-xl md:text-2xl text-white":"text-lg text-white/65"}`}>{p}</motion.p>)}</div><div className="mt-12 pt-8 border-t border-white/10 text-[#d4a574] font-serif italic text-lg">A foundation is often built quietly.</div></Card></Shell>}
    {step===4&&<Shell eyebrow="Chapter III" title={s.unknown.title} onNext={next} onBack={back}><div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4">{memories.map((m:any,i:number)=><button key={i} onClick={()=>setOpen(open===i?null:i)} className="text-left"><Card className={`p-6 h-full transition ${open===i?"border-[#d4a574]/50":"hover:border-white/20"}`}><span className="text-[#d4a574] font-mono text-xs">MEMORY {String(i+1).padStart(2,"0")}</span><p className="mt-4 font-serif text-lg text-white/75">{m.text}</p>{open===i&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="mt-6 pt-5 border-t border-white/10"><p className="text-sm text-white/45">A story placeholder — add the real memory here later.</p><div className="mt-4 h-24 rounded-xl border border-dashed border-[#d4a574]/30 flex items-center justify-center text-[10px] uppercase tracking-widest text-[#d4a574]/60">Story / photo placeholder</div></motion.div>}</Card></button>)}</div></Shell>}
    {step===5&&<Shell eyebrow="Chapter IV" title={s.receipts.title} onNext={next} onBack={back}><div className="grid md:grid-cols-2 gap-8 items-center"><div className="grid grid-cols-2 gap-3">{s.receipts.investments.map((x:string,i:number)=><Card key={x} className="p-5"><p className="text-[#d4a574] text-[10px] tracking-widest uppercase">{String(i+1).padStart(2,"0")}</p><p className="mt-3 font-serif text-white/75">{x}</p></Card>)}</div><Card className="p-8 md:p-10"><p className="text-xs tracking-[.3em] uppercase text-[#d4a574]">The return</p><div className="mt-8 space-y-5 font-serif text-xl text-white/70"><p>You invested in a child.</p><p>The child grew.</p><p>And he's building things.</p><p>He's still learning.</p><p>Still dreaming.</p><p>Still becoming.</p></div><p className="mt-8 pt-7 border-t border-white/10 text-[#d4a574] font-serif italic text-xl">Maybe that's one of the greatest returns an uncle can ever receive.</p></Card></div></Shell>}
    {step===6&&<Shell eyebrow="Chapter V" title="50 Years, 50 Words" onNext={next} onBack={back}><div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-5 gap-3">{words.map((w,i)=><button key={i} onClick={()=>setOpen(open===i?null:i)} className={`min-h-24 rounded-xl border p-3 flex flex-col items-center justify-center transition ${open===i?"border-[#d4a574]/60 bg-[#d4a574]/10":"border-white/10 bg-white/[.025] hover:bg-white/[.06]"}`}><span className="text-[9px] text-white/25 font-mono">{String(i+1).padStart(2,"0")}</span><span className="mt-2 font-serif text-white/80">{w}</span>{open===i&&<span className="mt-2 text-[10px] text-[#d4a574]">A reason to remember.</span>}</button>)}</div><p className="text-center text-white/30 mt-7 text-sm">Tap the words. Every one has a story waiting behind it.</p></Shell>}
    {step===7&&<Shell eyebrow="Chapter VI" title={s.familyVoices.title} onNext={next} onBack={back}><div className="max-w-3xl mx-auto grid sm:grid-cols-2 gap-4">{voices.map((v:any,i:number)=><Card key={v.name} className="p-6"><div className="flex items-center gap-4"><div className="w-12 h-12 rounded-full border border-[#d4a574]/30 flex items-center justify-center text-[#d4a574]">{i+1}</div><div><p className="font-serif text-lg">{v.name}</p><p className="text-[10px] tracking-widest uppercase text-white/30">Family voice</p></div></div><div className="mt-6 h-16 rounded-xl border border-dashed border-[#d4a574]/30 flex items-center justify-center gap-3 text-[#d4a574]/65"><span className="text-xl">◉</span><span className="text-xs tracking-widest uppercase">Voice note placeholder</span></div><p className="mt-4 text-xs text-white/35">Replace with a short recording: “What's one thing you are grateful to him for?”</p></Card>)}</div></Shell>}
    {step===8&&<Shell eyebrow="Chapter VII" title={s.manAt50.title} onNext={next} onBack={back}><div className="relative max-w-4xl mx-auto min-h-[480px] flex flex-col items-center justify-center"><div className="absolute inset-x-0 top-1/2 h-px bg-gradient-to-r from-transparent via-[#d4a574]/40 to-transparent"/><div className="flex items-end gap-5 md:gap-12 relative"><div className="text-center"><div className="text-7xl md:text-9xl font-serif text-[#d4a574]">50</div><p className="text-[10px] tracking-widest text-white/35">TODAY</p></div><div className="text-4xl text-white/20 pb-5">→</div><div className="text-center pb-2"><div className="text-4xl md:text-6xl font-serif text-white/45">60</div></div><div className="text-4xl text-white/15 pb-5">→</div><div className="text-center pb-4"><div className="text-4xl md:text-6xl font-serif text-white/30">70</div></div><div className="text-4xl text-white/10 pb-5">→</div><div className="text-center pb-6"><div className="text-4xl md:text-6xl font-serif text-white/20">?</div></div></div><div className="mt-16 max-w-2xl text-center space-y-5 font-serif text-xl md:text-2xl text-white/65">{s.manAt50.lines.map((x:string,i:number)=><motion.p key={i} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.25}}>{x}</motion.p>)}</div><p className="mt-10 text-[#d4a574] font-serif italic text-2xl">{s.manAt50.closing}</p></div></Shell>}
    {step===9&&<Shell eyebrow="One Last Thing" title="The Gift" onNext={next} onBack={back}><div className="max-w-xl mx-auto text-center"><AnimatePresence mode="wait">{!archive?<motion.div key="closed" initial={{opacity:0}} animate={{opacity:1}}><p className="font-serif text-xl text-white/55 mb-10">This isn't something I bought.<br/>It's something I wanted you to have.</p><button onClick={()=>setArchive(true)} className="px-10 py-5 rounded-full border border-[#d4a574]/60 bg-[#d4a574]/10 text-[#d4a574] tracking-[.25em] text-xs hover:bg-[#d4a574]/20 transition">{s.surprise.buttonText}</button></motion.div>:<motion.div key="open" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><Card className="p-8 md:p-12"><p className="text-[10px] tracking-[.35em] uppercase text-[#d4a574]">The Family Archive</p><h3 className="mt-5 text-4xl md:text-5xl font-serif">THE FAMILY NAME<br/><span className="text-[#d4a574]">ARCHIVE</span></h3><p className="mt-6 text-white/55 font-serif leading-relaxed">A place for photographs, voices, stories, letters, and the memories that made this family what it is.</p></Card></motion.div>}</AnimatePresence></div></Shell>}
    {step===10&&<Shell eyebrow="A Letter" title="For You" onNext={next} onBack={back}><Card className="max-w-3xl mx-auto p-8 md:p-14"><div className="space-y-5 font-serif text-lg leading-relaxed text-white/70">{s.letter.paragraphs.map((p:string,i:number)=><motion.p key={i} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.12}}>{p}</motion.p>)}</div></Card></Shell>}
    {step===11&&<section className="min-h-screen flex items-center justify-center px-6 text-center relative overflow-hidden bg-black"><div className="max-w-4xl"><div className="grid grid-cols-2 md:grid-cols-3 gap-3 opacity-70">{Array.from({length:6}).map((_,i)=><div key={i} className="aspect-[4/3] rounded-xl border border-white/10 bg-white/[.03] flex items-center justify-center text-[10px] tracking-widest uppercase text-white/25">Photo {i+1}</div>)}</div><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.8,duration:1.2}} className="mt-12"><p className="text-4xl md:text-6xl font-serif">50 YEARS.</p><p className="text-4xl md:text-6xl font-serif text-[#d4a574]">ONE LIFE.</p><p className="text-4xl md:text-6xl font-serif">COUNTLESS LIVES TOUCHED.</p><p className="mt-10 text-[#d4a574] uppercase tracking-[.35em] text-xs">Happy 50th, Uncle. ❤️</p><p className="mt-5 text-white/45 font-serif italic text-lg">Your story isn't finished.</p></motion.div></div></section>}
   </motion.div>
  </AnimatePresence>
 </main>
}